In [2]:
import numpy as np
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


 # Get a specific element

In [3]:
a[1,5]

13

# Get a specific row

In [4]:
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [5]:
a[1,:]

array([ 8,  9, 10, 11, 12, 13, 14])

# Get a specific coloumn

In [6]:
a[:,2]

array([ 3, 10])

# [startindex:endindex:stepsize]

In [7]:
a[0,1:6:2]

array([2, 4, 6])

In [8]:
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


# update an elements

In [9]:
a[1,5]=27
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 27 14]]


In [10]:
a[:,2]=5
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 27 14]]


In [11]:
a[1,:]=21
print(a)

[[ 1  2  5  4  5  6  7]
 [21 21 21 21 21 21 21]]


In [12]:
a[:,2]=[18,19]
print(a)

[[ 1  2 18  4  5  6  7]
 [21 21 19 21 21 21 21]]


# 3-d Array

In [13]:
b=np.array([[[1,2],[3,4],[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]


In [14]:
print(b[0,:,:])

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


# Initializing Different types of Array

In [15]:
# all 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [16]:
# all 0s matrix
np.zeros((2,3,3),dtype='int32')

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]])

In [17]:
# all 1s matrix
np.ones((4,2,2),dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [18]:
# any other number
np.full((2,2),27)

array([[27, 27],
       [27, 27]])

In [19]:
# any other number (full_like)
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [20]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.65984577, 0.84766713],
       [0.83326728, 0.64978817],
       [0.22151788, 0.69363075],
       [0.71823068, 0.87904834]])

In [21]:
np.random.randint(-4,8, size=(3,3))

array([[ 2,  1, -1],
       [-2, -3, -1],
       [ 6, -1,  6]])

In [22]:
# identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# copy and other operations

In [23]:
a=np.array([1,2,3])
b=a
b[0]=100
print(a)

[100   2   3]
