import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

In [1]:
#Use a tuple to create a NumPy array:

import numpy as np

arr = np.array((1, 2, 3, 4, 5))

print(arr)

[1 2 3 4 5]


In [2]:
#Create a 0-D array with value 42

import numpy as np

arr = np.array(42)

print(arr)

42


In [3]:
#Create a 1-D array containing the values 1,2,3,4,5:

import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [4]:
#Create a 2-D array containing two arrays with the values 1,2,3 and 4,5,6:

import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


In [5]:
#Create a 3-D array with two 2-D arrays, both containing two arrays with the values 1,2,3 and 4,5,6:

import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [6]:
#Check how many dimensions the arrays have:

import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


# Numpy Array indexing

In [7]:
#Get the first element from the following array:

import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[0])

1


In [8]:
#Get the second element from the following array.

import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[1])

2


In [9]:
#Get third and fourth elements from the following array and add them.

import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[2] + arr[3])


7


In [10]:
#Access the element on the first row, second column:

import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st row: ', arr[0, 1])


2nd element on 1st row:  2


In [11]:
#Access the element on the 2nd row, 5th column:

import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('5th element on 2nd row: ', arr[1, 4])


5th element on 2nd row:  10


In [12]:
#Access the third element of the second array of the first array:

import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])

6


In [13]:
#Access the third element of the second array of the first array:

import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [14]:
#Access the third element of the second array of the first array:

import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[1, 1, 2])

12


In [15]:
#Print the last element from the 2nd dim:

import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1])


Last element from 2nd dim:  10


 # Slicing

In [16]:
#Slice elements from index 1 to index 5 from the following array:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

[2 3 4 5]


In [17]:
#Slice elements from index 4 to the end of the array:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[4:])

[5 6 7]


In [18]:
#Slice elements from the beginning to index 4 (not included):

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[:4])

[1 2 3 4]


In [19]:
#Slice from the index 3 from the end to index 1 from the end:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])

[5 6]


In [20]:
#Return every other element from index 1 to index 5:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])

[2 4]


In [21]:
#Return every other element from the entire array:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[::2])

[1 3 5 7]


In [22]:
#From the second element, slice elements from index 1 to index 4 (not included):

import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])


[7 8 9]


In [23]:
#From both elements, return index 2:

import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 2])

[3 8]


In [24]:
#From both elements, slice index 1 to index 4 (not included), this will return a 2-D array:

import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 1:4])


[[2 3 4]
 [7 8 9]]


In [25]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr.dtype)


int32


In [26]:
#Get the data type of an array containing strings:

import numpy as np

arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)

<U6


In [27]:
#Create an array with data type 4 bytes integer:

import numpy as np

arr = np.array([1, 2, 3, 4], dtype='i4')

print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [28]:
#Print the shape of a 2-D array:

import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


In [29]:
#Create an array with 5 dimensions using ndmin using a vector with values 1,2,3,4 and verify that last dimension has value 4:

import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)


[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


In [30]:
#Convert the following 1-D array with 12 elements into a 2-D array.

#The outermost dimension will have 4 arrays, each with 3 elements:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [31]:
#Convert the following 1-D array with 12 elements into a 3-D array.

#The outermost dimension will have 2 arrays that contains 3 arrays, each with 2 elements:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)


[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


# numpy of Darsan

In [32]:
import numpy as np
a=np.array(['shibu','shakshi','sonu','simran'])
print(a)
print(type(a))

['shibu' 'shakshi' 'sonu' 'simran']
<class 'numpy.ndarray'>


# arange(start,end,step)

In [33]:
import numpy as np
b=np.arange(0,10,1)
print(b)

[0 1 2 3 4 5 6 7 8 9]


In [34]:
import numpy as np
b=np.arange(0,10,2)
print(b)

[0 2 4 6 8]


In [35]:
import numpy as np
b=np.arange(0,10,3)
print(b)

[0 3 6 9]


In [36]:
import numpy as np
b=np.arange(2,10,5)
print(b)

[2 7]


# Zeros()

In [37]:
import numpy as np
a=np.zeros(3)
print(a)

[0. 0. 0.]


In [38]:
import numpy as np
a1=np.zeros((3,3))
print(a1)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


# eye()

In [39]:
import numpy as np
a=np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [40]:
import numpy as np
a=np.eye(4,5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]


# linspace(start,stop,num)()

In [41]:
import numpy as np
a=np.linspace(0,1,11)
print(a)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


In [42]:
import numpy as np
a=np.linspace(0,2,11)
print(a)

[0.  0.2 0.4 0.6 0.8 1.  1.2 1.4 1.6 1.8 2. ]


# rand()

In [43]:
import numpy as np
r1=np.random.rand()
print(r1)

0.7981038601748572


In [44]:
import numpy as np
r1=np.random.rand(3,2)# no tuple
print(r1)

[[0.2416343  0.81948322]
 [0.23461504 0.35802369]
 [0.17840016 0.16214508]]


# randint(low,high,num)()

In [45]:
import numpy as np
r2=np.random.randint(1,100,10)
print(r2)


[44 43 54 25 29 50 82 38 19  3]


# Aggregations:-

# min()

In [46]:
import numpy as np
l=[1,5,3,8,2,3,6,7,5,2,9,11,2,5,3,4,8,9,3,1,9,3]
a=np.array(l)
print('min way1 = ',a.min())

min way1 =  1


# max()

In [47]:
import numpy as np
l=[1,5,3,8,2,3,6,7,5,2,9,11,2,5,3,4,8,9,3,1,9,3]
a=np.array(l)
print('max way1 = ',a.max())

max way1 =  11


In [48]:
import numpy as np
l=[1,5,3,8,2,3,6,7,5,2,9,11,2,5,3,4,8,9,3,1,9,3]
a=np.array(l)
print('min = ',a.min())
print('Argmin = ',a.argmin())
print('max = ',a.max())
print('ArgMax = ',a.argmax())
print('sum = ',a.sum())
print('Mean = ',a.mean())
print('Std = ',a.std())

min =  1
Argmin =  0
max =  11
ArgMax =  11
sum =  109
Mean =  4.954545454545454
Std =  2.9151215899679936


In [49]:
import numpy as np
l=[7,5,3,1,8,2,3,6,11,5,2,9,10,2,5,3,7,8,9,3,1,9,3]
a=np.array(l)
print('min = ',a.min())
print('Argmin = ',a.argmin())
print('max = ',a.max())
print('ArgMax = ',a.argmax())
print('sum = ',a.sum())
print('Mean = ',a.mean())
print('Std = ',a.std())

min =  1
Argmin =  3
max =  11
ArgMax =  8
sum =  122
Mean =  5.304347826086956
Std =  3.042235771223635


# Slicing ndarray

In [50]:
import numpy as np
arr=np.array(['a','b','c','d','e','f','g','h'])
print(arr[1:4])
print(arr[:5])
print(arr[5:])
print(arr[2:7:2])
print(arr[::-1])

['b' 'c' 'd']
['a' 'b' 'c' 'd' 'e']
['f' 'g' 'h']
['c' 'e' 'g']
['h' 'g' 'f' 'e' 'd' 'c' 'b' 'a']


In [51]:
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]])
print(arr[2][3])
print(arr[2,3])
print(arr[2])
print(arr[0:2])
print(arr[0:2:2])
print(arr[::-1])
print(arr[1:3,1:3])
print(arr[3:,:3])
print(arr[:,::-1])

14
14
[11 12 13 14 15]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[1 2 3 4 5]]
[[21 22 23 24 25]
 [16 17 18 19 20]
 [11 12 13 14 15]
 [ 6  7  8  9 10]
 [ 1  2  3  4  5]]
[[ 7  8]
 [12 13]]
[[16 17 18]
 [21 22 23]]
[[ 5  4  3  2  1]
 [10  9  8  7  6]
 [15 14 13 12 11]
 [20 19 18 17 16]
 [25 24 23 22 21]]


In [52]:
import numpy as np
arr=np.array([['a','b','c'],['d','e','f'],['g','h','i']])
print(arr[0:2,0:2])
print(arr[:,::-1])
print(arr[::-1,::-1])


[['a' 'b']
 ['d' 'e']]
[['c' 'b' 'a']
 ['f' 'e' 'd']
 ['i' 'h' 'g']]
[['i' 'h' 'g']
 ['f' 'e' 'd']
 ['c' 'b' 'a']]


# DataFrame

In [53]:
import pandas as pd
df=pd.DataFrame({'name':['Shibu','simaran','sonam'],'Marks':[44,55,66]})
print(df)

      name  Marks
0    Shibu     44
1  simaran     55
2    sonam     66


# Numpy

In [54]:
import numpy as np
b=np.arange(0,10,2)
print(b)

[0 2 4 6 8]


In [55]:
import numpy as np
b=np.zeros(2)
print(b)

[0. 0.]


In [56]:
import numpy as np
b=np.zeros((3,1))
print(b)

[[0.]
 [0.]
 [0.]]


In [57]:
import numpy as np
b=np.eye(10,10)
print(b)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [58]:
import numpy as np
b=np.linspace(1,4,7)
print(b)

[1.  1.5 2.  2.5 3.  3.5 4. ]


In [59]:
import numpy as np
b=np.zeros((3,3))
print(b.shape)

(3, 3)


In [60]:
import numpy as np
res=np.random.randint(1,100,10)
res2=res.reshape(5,2)
print(res2)

[[60 66]
 [57 47]
 [43  7]
 [ 5 70]
 [39 91]]


In [61]:
import numpy as np
res=np.random.rand()
print(res)

0.1529949377396358


In [62]:
import numpy as np
res=np.random.randint(1,100,10)
print(res)

[87 73  2 88 78 86 87  3 88 76]


In [63]:
import numpy as np
res=np.random.randn()
print(res)

-1.1355561111684325


In [64]:
import numpy as np
res=np.random.rand(3,3)
print(res)

[[0.68191508 0.90192088 0.76608051]
 [0.77157066 0.39472566 0.99167814]
 [0.27957305 0.08545757 0.73128557]]


In [65]:
import numpy as np
l=[4,5,6,78,2,7,0]
b=np.array(l)
#print('Min Way1= ',b.min())
print(b.min())

0


In [66]:
l=[4,5,6,78,2,7,0]
b=np.array(l)
#print('Min Way1= ',b.min())
print(b.max())

78


In [67]:
import numpy as np
l=[3,4,5,6,7,11,1,1,1,67,89,67,67,67,0,0,0,0,0,]
b=np.array(l)
print('min = ',b.min())
print('ArgMin = ',b.argmin())
print('max = ',b.max())
print('ArgMax= ',b.argmax())
print('sum = ',b.sum())
print('mean = ',b.mean())
print('std = ',b.std())

min =  0
ArgMin =  14
max =  89
ArgMax=  10
sum =  396
mean =  20.842105263157894
std =  30.67874827250726


In [68]:
import numpy as np
array2d=np.array([[2,3,4],[4,6,7],[1,9,7]])
print('sum= ',array2d.sum())

sum=  43


In [69]:
import numpy as np
array2d=np.array([[2,3,4],[4,6,7],[1,9,7]])
print('sum (col) = ',array2d.sum(axis=0))#v
print('sum (row) = ',array2d.sum(axis=1))#h

sum (col) =  [ 7 18 18]
sum (row) =  [ 9 17 17]


In [70]:
import numpy as np
arr=np.array(['a','b','c','d','e','f','g','h','i','j','k'])
print(arr[0:10])
print(arr[:11])
print(arr[0:5])
print(arr[1:10])
print(arr[2:])
print(arr[2:7:2])
print(arr[::-1])

['a' 'b' 'c' 'd' 'e' 'f' 'g' 'h' 'i' 'j']
['a' 'b' 'c' 'd' 'e' 'f' 'g' 'h' 'i' 'j' 'k']
['a' 'b' 'c' 'd' 'e']
['b' 'c' 'd' 'e' 'f' 'g' 'h' 'i' 'j']
['c' 'd' 'e' 'f' 'g' 'h' 'i' 'j' 'k']
['c' 'e' 'g']
['k' 'j' 'i' 'h' 'g' 'f' 'e' 'd' 'c' 'b' 'a']


In [71]:
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]])
print(arr[2][3])
print(arr[2,2])
print(arr[2])
print(arr[0:2])
print(arr[0:2:2])
print(arr[::-1])
print(arr[1:3,1:3])
print(arr[3:,:3])
print(arr[:,::-1])

14
13
[11 12 13 14 15]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[1 2 3 4 5]]
[[21 22 23 24 25]
 [16 17 18 19 20]
 [11 12 13 14 15]
 [ 6  7  8  9 10]
 [ 1  2  3  4  5]]
[[ 7  8]
 [12 13]]
[[16 17 18]
 [21 22 23]]
[[ 5  4  3  2  1]
 [10  9  8  7  6]
 [15 14 13 12 11]
 [20 19 18 17 16]
 [25 24 23 22 21]]


In [72]:
import numpy as np
import pandas as pd
randArr=np.random.randint(0,100,20).reshape(5,4)
df=pd.DataFrame(randArr,np.arange(101,106,1),['PDS','Algo','SE','INS'])
print(df)

     PDS  Algo  SE  INS
101    7    63  33   33
102   25    59   4   68
103   92    65  49   92
104   80    81  79   72
105   34    54  70   52


In [73]:
import numpy as np
import pandas as pd
randArr=np.random.randint(0,100,20).reshape(5,4)
df=pd.DataFrame(randArr,np.arange(101,106,1),['PDS','Algo','SE','INS'])
print(df['Algo'])

101    21
102    78
103    87
104    16
105    43
Name: Algo, dtype: int32


In [74]:
import numpy as np
import pandas as pd
randArr=np.random.randint(0,100,20).reshape(5,4)
df=pd.DataFrame(randArr,np.arange(101,106,1),['PDS','Algo','SE','INS'])
print(df.loc[101])
#print(df.loc[101],'PDS')


PDS     58
Algo    55
SE      12
INS     53
Name: 101, dtype: int32


In [75]:
import numpy as np
import pandas as pd
randArr=np.random.randint(0,100,20).reshape(5,4)
df=pd.DataFrame(randArr,np.arange(101,106,1),['PDS','Algo','SE','INS'])
print(df>50)

       PDS   Algo     SE    INS
101   True   True  False   True
102   True  False  False  False
103  False  False   True   True
104   True  False  False   True
105  False  False  False   True
