# one dimensional array

In [28]:
import numpy as np
a=np.array([1,2,3,4])
print(a)
print(type(a))
a.ndim
a.dtype



[1 2 3 4]
<class 'numpy.ndarray'>


dtype('int32')

In [20]:
a.shape

(4,)

In [27]:
a.itemsize

4

In [30]:
a.nbytes

16

# twodim array

In [5]:
b=np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [21]:
print(b)
print(type(a))
b.ndim



[[9. 8. 7.]
 [6. 5. 4.]]
<class 'numpy.ndarray'>


2

In [29]:
b.itemsize

8

In [33]:
#Get total size
b.nbytes

48

In [32]:
# get number of elements
b.size

6

# get Shape

In [34]:
# Get row and coluomn
b.shape


(2, 3)

# reshape

In [24]:
x=np.array([1,2,3,4,5,6])
print(x)
y=x.reshape(2,3)
print(y)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


# Accessinchanging Specific Elements,Rows,Column etc

In [10]:
import numpy as np
d=np.array([[1,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(d)
d[1,5]

[list([1, 3, 4, 5, 6, 7]) list([8, 9, 10, 11, 12, 13, 14])]


<ipython-input-10-c04a76913679>:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  d=np.array([[1,3,4,5,6,7],[8,9,10,11,12,13,14]])


IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [8]:
d[1,5]

NameError: name 'd' is not defined